apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: 842565575067.dkr.ecr.ap-south-1.amazonaws.com/infra-redis-cluster-production:1.0.1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
          protocol: TCP
      resources:
        limits:
          cpu: "1.5"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: 842565575067.dkr.ecr.ap-south-1.amazonaws.com/infra-redis-cluster-production:1.0.1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
          protocol: TCP
  volumes:
    - name: data
      emptyDir: {}
